spring.application.name=FlightReservationSystem

spring.datasource.url=jdbc:postgresql://111.118.176.81:6000/testdb
spring.datasource.username=appuser
spring.datasource.password=appuser@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8085/realms/FlightReservationSystem
keycloak.url=http://localhost:8085/realms/FlightReservationSystem/protocol/openid-connect/token
keycloak.client-id=flight-client
keycloak.client-secret=lmNzJZDDd4g6GJ7LWvJdIWjRKKquPkFN

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rajapriyanka2025@gmail.com
spring.mail.password=bhobmpgaqwdstpvd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
